name: fs
main: com.nott.fs.plugins.MyPlugin
version: 1.0
description: A plugin for Bukkit and Spigot.
author: Nott
#commands:
#  hello:
#    description: Say hello to someone.
#    usage: /<command> [message]